[package]
name = "untitled"
version = "0.1.0"
edition = "2024"

[dependencies]
file = "1.1.2"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
text_io = "0.1.13"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
